# Generated by Django 2.2.3 on 2019-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ele', models.IntegerField()),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
