# Generated by Django 2.2.3 on 2019-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0002_ppi_img_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hei', models.IntegerField()),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
    ]
