# Generated by Django 2.2.3 on 2019-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0003_cappi'),
    ]

    operations = [
        migrations.CreateModel(
            name='WINDTHI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10)),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
    ]
