# Generated by Django 2.2.3 on 2019-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0005_rhi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBS5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusion', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusion', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusion', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
    ]
