# Generated by Django 2.2.3 on 2019-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0006_dbs5_profile_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlogP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
    ]
