# Generated by Django 2.2.3 on 2019-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0007_tlogp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindDirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hei', models.IntegerField()),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hei', models.IntegerField()),
                ('station', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
    ]
