# Generated by Django 2.2.3 on 2019-07-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0008_winddirect_windspeed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WindDirect',
            new_name='Lidar',
        ),
        migrations.DeleteModel(
            name='WindSpeed',
        ),
    ]
