# Generated by Django 2.2.3 on 2019-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0009_auto_20190715_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempHumidityMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WindCurveMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WindRoseDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hei', models.IntegerField()),
                ('station', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WindRoseMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hei', models.IntegerField()),
                ('station', models.CharField(max_length=50)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
    ]
