# Generated by Django 2.2.3 on 2019-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0010_temphumiditymonth_windcurvemonth_windrosedaily_windrosemonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphumiditymonth',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='temphumiditymonth',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='windcurvemonth',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='windcurvemonth',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='windrosedaily',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='windrosemonth',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='windrosemonth',
            name='date_to',
            field=models.DateField(),
        ),
    ]
