# Generated by Django 2.2.3 on 2019-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindServer', '0011_auto_20190801_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('img_src', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='TempHumidityMonth',
            new_name='HumidityMonth',
        ),
    ]
